version: '3'
services:
  api:
    build:
      context: ""
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./dist:/usr/src/app/dist
    environment:
      - NODE_ENV=dev
      - MYSQL_USER=root
      - MYSQL_PASS=
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=demo
    image: api:latest
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    container_name: ste
    expose:
      - "3000"
    command: npm run nodemon
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
