version: '3'
services:
  api:
    build:
      context: ""
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=dev
    image: api:latest
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - mysql
    container_name: ste
    expose:
      - "3000"
    command: npm run nodemon
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    expose:
      - "3308:3306"
